/*
 * This source file was generated by the Gradle 'init' task
 */
package calculadoranucleo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.sumar(0, 0), "app should have a greeting");
    }
}
