/*
 * This source file was generated by the Gradle 'init' task
 */
package calculadoranucleo;
import java.util.Scanner;
public class App {
     // Función para sumar dos números
     public static double sumar(double a, double b) {
        return a + b;
    }
    
    // Función para restar dos números
    public static double restar(double a, double b) {
        return a - b;
    }

    // Función para multiplicar dos números
    public static double multiplicar(double a, double b) {
        return a * b;
    }

    // Función para dividir dos números
    public static double dividir(double a, double b) {
        if (b == 0) {
            System.out.println("Error: No se puede dividir entre cero.");
            return Double.NaN;
        }
        return a / b;
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("Bienvenido a la calculadora simple");
        System.out.println("Elige una operación:");
        System.out.println("1. Suma");
        System.out.println("2. Resta");
        System.out.println("3. Multiplicación");
        System.out.println("4. División");

        int opcion = scanner.nextInt();

        System.out.print("Introduce el primer número: ");
        double numero1 = scanner.nextDouble();

        System.out.print("Introduce el segundo número: ");
        double numero2 = scanner.nextDouble();

        double resultado;

        switch (opcion) {
            case 1:
                resultado = sumar(numero1, numero2);
                System.out.println("El resultado de la suma es: " + resultado);
                break;
            case 2:
                resultado = restar(numero1, numero2);
                System.out.println("El resultado de la resta es: " + resultado);
                break;
            case 3:
                resultado = multiplicar(numero1, numero2);
                System.out.println("El resultado de la multiplicación es: " + resultado);
                break;
            case 4:
                resultado = dividir(numero1, numero2);
                if (!Double.isNaN(resultado)) {
                    System.out.println("El resultado de la división es: " + resultado);
                }
                break;
            default:
                System.out.println("Opción no válida");
        }

        scanner.close();
    }
}
